### PR TITLE
Additional Meta Scopes

### PR DESCRIPTION
**Pull request by francescomari**
I'd like to use this library to exchange for access tokens using various other meta scopes. Formally defining each and including a corresponding case statement feels heavy. Has there been any discussion on opening this area up more, perhaps by allowing passing an array of strings for the meta scopes?

EDIT: The issue was originally posted by @remear, but I messed it up. For a full description of what went wrong, see my comment below.

### CODE REVIEW

**Comment by francescomari** [comment]
@remear I'm so sorry about how this issue turned out. I wanted to attach a branch to the issue you opened to discuss a technical solution. I followed [this post](https://jtway.co/convert-github-issue-to-pull-request-c624834835d8) to convert an issue into a PR, but `hub` messed up the original comment (it looks like I was the one opening the issue). I'm never going to try to use this trick anymore and open separate PRs for this use case. Please forgive the mess.

If it's fine for you, what about discussing the code change? I think it requires some thought, because it's going to break the compatibility with existing consumers of the library.

**Comment by francescomari** [comment]
It actually occurred to me that I don't have to remove the current way of specifying meta-scopes. I can simply mark them for deprecation and add a separate mechanism for adding arbitrary claims to the JWT token.

**Comment by remear** [comment]
No worries about the issue history. 🙂 

I like the implementation here. The convenience of building the meta scope claims using the Client URL is nice, but there's nothing that guarantees the current format will never change. The explicit claims should add great future flexibility.

**Comment by francescomari** [comment]
Thanks for your feedback. I will squash and merge my changes, and cut v0.6.0 after that.

**Comment by francescomari** [comment]
@remear I've created v0.6.0 with these changes. You should be able to upgrade the dependency in your project.

**Comment by remear** [comment]
Fantastic, and thanks very much for doing this!

**Pull request merged**
